server:
  port: 8081

spring:
  application:
    name: investments
  datasource:
    url: jdbc:postgresql://localhost:5432/investments_db
    username: ldamuleli
    password: Lodav72#
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
    schema: public
    enabled: true
    user: ldamuleli
    password: Lodav72#
    baseline-description: "init"
    baseline-version: 1

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    filter:
      order: 10

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jwt:
  secret : cDJ3DacmMbxoQnVUyS15IYBCyJxSgKcdqtjDn5AKP0Av3dS7ZAivAzsfijxF88R8sbAR/i6pssz7zvcF4E8+dw==

